run:
  tests: false
  timeout: 5m
  build-tags: []
  go: '1.24'

issues:
  max-issues-per-linter: 75
  max-same-issues: 5

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - gomodguard
    - goimports
    - dupl
    - errname
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - gosec
    - importas
    - intrange
    - nestif
    - maintidx
    - makezero
    - misspell
    - mnd
    - perfsprint
    - prealloc
    - testpackage
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - usestdlibvars
    - unused

linters-settings:
  goimports:
    local-prefixes: "github.com/vpbuyanov/syncplay/"
  wrapcheck:
    ignorePackageGlobs:
      - github.com/labstack/echo/*

