name: CD Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy via Helm
        run: |
          helm upgrade --install syncplay ./charts/syncplay \
            --namespace syncplay \
            --set image.tag=${{ github.sha }} \
            --wait --timeout 5m
